name: getx_v463
description: "GetX v4.6.3 project."


publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  ansicolor: ^2.0.1
  get: ^4.6.3
  # local 저장소
  get_storage: ^2.0.3
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0



flutter:
  
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  
  
